services:
  backend:
    build: 
      context: ./controledeservico
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5371:5371"